-- Statute-of-limitations engine, foundation: a deterministic lookup
-- table, never an AI-generated answer. Concrete reason this matters: the
-- Operator was once asked a real Texas custody question and cited
-- "Tex. Fam. Code §156.002" — the correct section, verified against
-- primary sources, is §156.102. The substance was right; the citation
-- was fabricated and went unnoticed until independently checked. A
-- missed or wrong statute-of-limitations deadline is legal malpractice.
-- This table exists so a rule-generated deadline traces to a citation a
-- human verified, not to a model's best guess — see the RLS section
-- below for how that boundary is enforced at the database level, not
-- just as a frontend convention.
--
-- Global reference data, not tenant-scoped (no firm_id/tenant_id column
-- on purpose) — every firm in a given jurisdiction sees the same rule.
create table if not exists deadline_rules (
  id uuid primary key default gen_random_uuid(),
  country text not null,          -- ISO 3166-1 alpha-2, e.g. 'US'
  region text,                    -- e.g. 'TX'; nullable for a hypothetical future national-level rule
  practice_area text not null,    -- matches practice_areas.key convention (e.g. 'personal_injury')
  trigger_event text not null,    -- machine-readable: 'injury_date', 'death_date', 'breach_date', 'prior_order_date'
  duration_value integer not null,
  duration_unit text not null check (duration_unit in ('years', 'months', 'days')),
  -- 'deadline': must file by trigger + duration (the normal SOL shape).
  -- 'restriction': cannot file UNTIL trigger + duration has passed — the
  -- inverse. §156.102 needs this shape; forcing it into 'deadline' would
  -- make an EARLIEST filing date render as a due-by date, which is
  -- exactly backwards and exactly the kind of error this table exists
  -- to prevent.
  rule_type text not null check (rule_type in ('deadline', 'restriction')),
  exceptions text,                -- plain-language summary of named exceptions; not a modeled rules engine in this pass
  citation text not null,         -- exact statute citation — required, never inferred
  source_verified_at date not null,
  -- Placeholder for future court-holiday-aware calculation. NOT
  -- implemented in this pass — every seed row below is calendar-day/
  -- month/year math, and the frontend disclaimer says so honestly.
  business_days_only boolean not null default false,
  notes text
);

-- ─────────────────────────────────────────────────────────────────────
-- RLS: read-only, for everyone authenticated, on purpose. This is the
-- database-level enforcement of "no AI write path to this table" — there
-- is no INSERT/UPDATE/DELETE policy defined below AT ALL, so once RLS is
-- enabled, every write from the anon/authenticated roles is rejected by
-- default, regardless of what any prompt or frontend code might attempt.
-- Editing this table is a migration-only operation, deliberately not
-- something an RLS policy could ever be written to allow from the app
-- layer. Not tenant-scoped (no tenant_id/firm_id to check against) — any
-- signed-in user, in any firm, in any jurisdiction, can read the full
-- table, since a Texas rule is only useful to a Texas firm looking it up
-- in the first place and there is nothing sensitive in statutory
-- reference data.
-- ─────────────────────────────────────────────────────────────────────
alter table deadline_rules enable row level security;

drop policy if exists "deadline_rules read" on deadline_rules;
create policy "deadline_rules read" on deadline_rules for select using (
  auth.uid() is not null
);

-- ─────────────────────────────────────────────────────────────────────
-- Seed data — exactly four rows, independently verified against primary
-- sources before this migration was written (not generated by this
-- migration). Do not add rows here by inference; expansion is a
-- deliberate, separately-verified process. Fixed ids + ON CONFLICT DO
-- NOTHING so this migration is safely re-runnable.
-- ─────────────────────────────────────────────────────────────────────
insert into deadline_rules
  (id, country, region, practice_area, trigger_event, duration_value, duration_unit, rule_type, exceptions, citation, source_verified_at, notes)
values
  (
    '10000000-0000-0000-0000-000000000001', 'US', 'TX', 'personal_injury', 'injury_date', 2, 'years', 'deadline',
    null,
    'Tex. Civ. Prac. & Rem. Code §16.003(a)', current_date,
    'Also covers property damage, trespass.'
  ),
  (
    '10000000-0000-0000-0000-000000000002', 'US', 'TX', 'personal_injury', 'death_date', 2, 'years', 'deadline',
    null,
    'Tex. Civ. Prac. & Rem. Code §16.003(b)', current_date,
    'Wrongful death — clock starts at death, not the underlying injury date.'
  ),
  (
    '10000000-0000-0000-0000-000000000003', 'US', 'TX', 'corporate', 'breach_date', 4, 'years', 'deadline',
    null,
    'Tex. Civ. Prac. & Rem. Code §16.004', current_date,
    'Applies to written and oral contracts alike; discovery rule may apply for concealed/latent breaches — flag for attorney judgment, don''t auto-resolve.'
  ),
  (
    '10000000-0000-0000-0000-000000000004', 'US', 'TX', 'family', 'prior_order_date', 1, 'years', 'restriction',
    'Endangerment affidavit; mutual consent of all parties; 6-month relinquishment of primary residence to another party.',
    'Tex. Fam. Code §156.102', current_date,
    'Restricts EARLY filing to change primary-residence designation — not a deadline to file by. The inverse shape of the other three rows in this table.'
  )
on conflict (id) do nothing;
